# Generated by Django 2.1 on 2019-03-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wine_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('designation', models.TextField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=0, max_digits=5)),
                ('price', models.IntegerField(null=True)),
                ('province', models.CharField(blank=True, max_length=150)),
                ('region_1', models.CharField(blank=True, max_length=150)),
                ('region_2', models.CharField(blank=True, max_length=150)),
                ('variety', models.CharField(blank=True, max_length=150)),
                ('winery', models.CharField(max_length=150)),
            ],
        ),
    ]
